# Generated by Django 3.1.5 on 2021-01-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckdetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='closetime',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='truck',
            name='opentime',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
