# Generated by Django 3.1.5 on 2021-01-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckdetails', '0002_auto_20210121_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='closetime',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
